version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
      - python -m pip install --upgrade --no-cache-dir mkdocs-material

    post_install:
      - poetry install --only doc
