version: 2

mkdocs:
  configuration: mkdocs.yaml

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_crate_enviroment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --only doc
