site_name: Notas Musicais
repo_url: https://github.com/azmovi
repo_name: azmovi/notas-musicais
edit_uri: tree/main/docs
theme: 
  name: material
  language: pt-BR
  logo: assets/logo.png
  favico: assets/logo.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css
